name: CI

on:
  push:
    branches:
    - editor

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Build the site in the robertobermejo/hugo container
      run: |
        docker run -v ${{ github.workspace }}:/srv/ robertobermejo/hugo:latest -s /srv
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Auto Commit changed files
      uses: stefanzweifel/git-auto-commit-action@v2.1.0
      branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}